apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - port: 5432        # Internal cluster port
      targetPort: 5432   # Port that PostgreSQL listens to inside the container
      nodePort: 30002    # External port on the node
